name: Build, Test, and Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Verify Environment Variables
      run: |
        if [ -z "${{ secrets.GCLOUD_SERVICE_KEY }}" ]; then
          echo "GCLOUD_SERVICE_KEY is not set."
          exit 1
        else
          echo "GCLOUD_SERVICE_KEY is set."
        fi

        if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
          echo "GCP_PROJECT_ID is not set."
          exit 1
        else
          echo "GCP_PROJECT_ID is set."
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.5.0
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and Push Docker image to Google Artifact Registry
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/token-validator-service/token-validator-service:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/token-validator-service/token-validator-service:latest


    - name: Deploy to Cloud Run (CLI)
      run: |
        gcloud run deploy token-validator-service \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/token-validator-service/token-validator-service:latest \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --service-account=gh-actions-pipeline@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
          --region=us-central1 \
          --platform=managed \
          --quiet \
          --no-allow-unauthenticated \
          --verbosity=debug
